# Generated by Django 4.2.20 on 2025-04-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
